version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: web_server_and_socket
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - d:\storage:/app/storage

